### ISSUE TITLE
Не понятно на каком порту работает приложение

### ISSUE THREAD

**Issue by VegasChickiChicki** [verhovensky/news-api#2]
После запуска по адресу http://127.0.0.1 начинает крутиться страница, но с 502 ошибкой, на 8000 вообще ничего нет.

**Comment by VegasChickiChicki** [comment]
Имеется ввиду после запуска докера

**Comment by verhovensky** [comment]
@VegasChickiChicki there are two ways you can find out the port of your web application running inside docker container.

1) You can verify that by running command:
```
docker ps
```

2) You can look at docker-compose.yml and verify, that it has lines:
```
newsapp:
        ...
        ports:
      - "8000:8000"
```
Meaning that application is accesible on port number 8000.

3) Please verify that you did not modify any of the files (docker-compose, requirements.txt and others)
Possibly, this behavior is triggered by django app failing to start because of missing dependency or dependencies.

**Comment by verhovensky** [comment]
Btw concerning migration - feel free to open another issue if you have problems running them.
Migrations are done normally if there is no cached images. I assume that you do have some cache / old images, db_data folder or  volume. 
You can verify  that entrypoint.sh runs migration process just after database becomes available.

https://github.com/verhovensky/news-api/blob/main/djnews/entrypoint.sh#L7

**Comment by VegasChickiChicki** [comment]
Локально у меня был запущен mysql на порту 3306, по этому менял порт на 3307(везде в приложении, через глобальный поиск), похоже было дело в этом. Освободил порт 3306, перезапустил и все заработало!
